export enum TimesheetNotificationType {
  TIMESHEET_SUBMITTED = 'TIMESHEET_SUBMITTED',
  TIMESHEET_APPROVED = 'TIMESHEET_APPROVED',
  TIMESHEET_REJECTED = 'TIMESHEET_REJECTED',
  TIMESHEET_DELETED = 'TIMESHEET_DELETED',
  TIMESHEET_RESTORED = 'TIMESHEET_RESTORED',
  EXPENSE_ADDED = 'EXPENSE_ADDED',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  PAYROLL_PROCESSED = 'PAYROLL_PROCESSED',
  CLOCK_EVENT_VERIFIED = 'CLOCK_EVENT_VERIFIED',
  CLOCK_EVENT_REJECTED = 'CLOCK_EVENT_REJECTED'
} 